### ISSUE TITLE
Invalid API Key?

### ISSUE THREAD

**Issue by 1n5aN1aC** [MoonshineSG/OctoPrint-Mobile#4]
This looks very promising, but the app is now giving me a "Invalid API Key" Message and not working, even after clearing the key, and re-copying it from the browser.

Interestingly, it seemed to work at first, but upon a reboot of the octoprint-running rasPi, I have not been able to get it to work any longer...

Any ideas what could be causing this?

Octoprint Version 1.3.0rc1 (rc/devel branch)

**Comment by MoonshineSG** [comment]
I am using the same branch, no problem. I don't have a user setup, but that shouldn't be an reason.

You're using the key under "Settings/API Key" and the "Enable" is checked. Right? 

A look at the log files might help.

**Comment by AlexanderPro29** [comment]
I also have this problem. The application has stopped working. Tried to change the API key - to solve the problem failed.

**Comment by 1n5aN1aC** [comment]
In my case, the API key got in a strange quantum state where it displayed, yet none would be saved to the config file.

I haven't had time to fix it quite yet, just providing more information that might help you.

**Comment by MoonshineSG** [comment]
@1n5aN1aC , thanks. You can try to edit the config.yaml manually and add in the api key. 

```
api:
  key: XXXXXXXXXXXXXXX
```

@AlexanderPro29, similar,  check the config.yaml and see if the key is there. if not, add it in manually.

**Comment by AlexanderPro29** [comment]
@MoonshineSG i'm checked the config.yaml (./home/pi/.octoprint/config.yaml) and see api key there. It coincides with the key in the iphone settings, but the app says "invalid API key".

**Comment by AlexanderPro29** [comment]
@MoonshineSG Is the key length is important in symbols?

**Comment by MoonshineSG** [comment]
The api key is handled by OctoPrint...  
Can you check if there are any spaces before or after the key (in the iOS app settings) ?

**Comment by AlexanderPro29** [comment]
@MoonshineSG I checked and found no spaces before / after the key or inside.

**Comment by MoonshineSG** [comment]
![2016-11-17_18-13-45](https://cloud.githubusercontent.com/assets/687747/20385248/aef7ac94-acf1-11e6-84a8-f7469b5e7aa5.png)

Just to be sure... This is the key you added. And it's enabled.

**Comment by MoonshineSG** [comment]
what version of OctoPrint ?

**Comment by AlexanderPro29** [comment]
Version: 1.3.0rc1.post0.dev0+gb38d181 (rc/devel branch)

**Comment by AlexanderPro29** [comment]
![image](https://cloud.githubusercontent.com/assets/23478523/20385397/10f5b35a-acd9-11e6-8946-36e61c850490.png)
I'm open settings and see them

**Comment by MoonshineSG** [comment]
you have a "n/a" instead of a key ...

**Comment by AlexanderPro29** [comment]
I filled out the field API key in the same code as in the iphone settings and hit "save", but the problem has not been solved.
If it can help, I have a public IP address, and API key of my OctoPi.

**Comment by MoonshineSG** [comment]
sure, i can try

**Comment by AlexanderPro29** [comment]
address pro29.telenet.ru:5000 
I created a user name/pass test/test
API key 7207F81507C346559C15794A5DFD1C98

**Comment by AlexanderPro29** [comment]
After restarting the server I have just successfully connected! The problem is solved, but it is not clear what it was. Server I rebooted before.

**Comment by MoonshineSG** [comment]
yes, i can see your printer :D 

now change your api key quickly!! :D

**Comment by AlexanderPro29** [comment]
Of course, I'll change the code)

**Comment by MoonshineSG** [comment]
anyway, I'm glad you got it sorted out.

**Comment by AlexanderPro29** [comment]
After replacing the API key problem persists. The key is stored in ./.octoprint/config.yaml, but for some reason that does not work ... I have removed completely the key in the web interface settings, copy it to the clipboard and through the web interface System> restart OctoPrint. Then again went into the settings and recorded the same key from the clipboard, and then to re-System> restart OctoPrint. Then again earned.

**Comment by MoonshineSG** [comment]
seams to be a problem with the apikey  in OctoPrint. I'll check with the OctoPrint developer..

**Comment by AlexanderPro29** [comment]
I am now convinced that adding / removing user helps in solving the problem. That is to API key to work, I added a new user via a web interface and rebooted OctoPrint, then the user can be deleted.

**Comment by MoonshineSG** [comment]
the api key should be user independent.. I don't even have a user in my octoprint... no login for me... :D

**Comment by AlexanderPro29** [comment]
However, this affects access. Even after a successful login and attempts to reconnect after a while, again, there is an error Invalid API key. Then I do OctoPi restarts and the plugin has successfully authenticated.

**Comment by MoonshineSG** [comment]
That is not a normal behaviour... I have never had this problem. 
I'm off on a short holiday but I'all have look at the problem when I'm back next week.

**Comment by 1n5aN1aC** [comment]
Yeah, I'm almost convinced this might be an issue in Octoprint itself perhaps.

I'm still having issues, have tried restarting the octoprint computer, re-entered API key, API is enabled, key appear in web GUI, key appears in config.yaml, same error.

I then changed the API key in the web GUI, clicked save, the config.yaml was updated, killed the app on my phone, changed the API key setting on my phone, and opened the app back up.  same problem.

I am honestly very confused as to why it worked int he very beginning, but then hasn't worked since.

**Comment by MoonshineSG** [comment]
I know this is not the most fun thing to do, but you might wana try to do a fresh OctoPrint setup.

**Comment by AlexanderPro29** [comment]
I also still have problems with a key. The application can successfully join, but after a while I receive an error when reconnect.

**Comment by 1n5aN1aC** [comment]
I'll try a reinstall once I get some more SD cards that I've been planning on buying anyways.  :P

**Comment by MoonshineSG** [comment]
@AlexanderPro29 , "an error" ? can you give the exact message and, if possible, under which exact conditions? What version of OctoPrint ? 
Maybe raise this under the OctoPrint support ? Seams to be something on their side. (I'll check as well, just in case)

@1n5aN1aC,  please let me know how it goes. Hopefully it helps.

**Comment by AlexanderPro29** [comment]
@MoonshineSG I meant the message "Invalid API key". Version: 1.3.0rc1.post0.dev0+gb38d181 (rc/devel branch)
I have yet to start to understand how it works github and English is not my native language. I apologize if my text is difficult to understand.

**Comment by MoonshineSG** [comment]
@AlexanderPro29 , no worries, Just needed more info to try to figure it out.  I'll check with OctoPrint to see if there's something they can help with.

**Comment by AlexanderPro29** [comment]
Today I installed Version: 1.3.0rc2 (rc / devel branch) to the latest version Raspbian, API key works. Later I will try to update the version installed on OctoPrint OctoPi.

**Comment by 1n5aN1aC** [comment]
@AlexanderPro29 can you confirm that the app continues to work after you did the reinstall?

**Comment by AlexanderPro29** [comment]
@1n5aN1aC Yes, the app works after a complete reinstall. (Formatting a SD card and a new installation)

**Comment by AlexanderPro29** [comment]
Today the problem is back. And Sli3cr program successfully see the printer, and Nautilus says "Invalid API key". I did not make any changes to the program, I do not understand what is connected with this error.

**Comment by MoonshineSG** [comment]
And the settings still shows the same API key? Did OctoPrint somehow generated a new API key?

**Comment by Monox83** [comment]
Hi, I had the same problem.
My Raspberry Pi is equipped with WLAN with Static IP. In my router it was with a second IP, this is not displayed in Pi, with this Andresse it works without problems.

**Comment by AlexanderPro29** [comment]
The problem in a mobile application, because other programs have successfully connected using the API. In the settings OctoPrint API has not changed. Sli3cr connects successfully, at the same time Nautilus reported "Invalid API key". The recently published update to OctoPrint rc03, the problem persists and the Nautilus is not working.

**Comment by MoonshineSG** [comment]
If using the same key and the same URL, it should work fine.  The message "Invalid API key" is from OctoPrint.. 
Can you share again your url/apikey ?  Let me try so see if I can spot anything

**Comment by AlexanderPro29** [comment]
I apologize for the delay in replying. Again I set up access to the address pro29.telenet.ru:5000 API key 55468C2C5CAA4C4F8A49EA71593943B9
I also created a test / test user
The printer is currently not connected due to a problem with the printer arduino. But the camera is connected.

**Comment by MoonshineSG** [comment]
i can see the live feed....

**Comment by analogmonster** [comment]
I am another user with the same issue.  I am on master 1.3.0, and nautilus 1.5.4 plugin on a PI3.  IOS app is up to date.  I did a clean octopi install yesterday (had a problem gonig from dev to master so did a clean master).  I dont have any other issues.  I have used the Octo app for IOS which also uses the API key, which I have to keep using until nautilus is behaving properly.  Octo is fully functioning.  However if I go to nautilus I get invalid API key.

I have tried changing the API key manually.  Once I did this Octo asked me to reconfigure, I gave it my new custom key, copied it to clipboard.  Tested and octo worked.  Do a paste of the key (which I am now certain is valid thanks to octo) into nautilus settings and still get invalid API key.  No spaces before or after.

It seems most likely this is at the IOS end rather than an Octoprint API key issue since I have no issues with another app.

**Comment by MoonshineSG** [comment]
@analogmonster And you're trying to access it via the same wifi ? 

@analogmonster @AlexanderPro29 can you paste your config.yaml  ?

**Comment by MoonshineSG** [comment]
@analogmonster what ios device  ?

**Comment by analogmonster** [comment]
same wifi same device same location.  I'm on octopi.local at the moment.  Also I always properly close the app before changing the API. Iphonr 6s plus  on 10.1.1

**Comment by analogmonster** [comment]
and I did have it working on my previous install when I was still on dev branch.  How do I get to my config.yaml, do you want me to ssh in or is there something I can do within octoprint?

**Comment by MoonshineSG** [comment]
Omul via ssh

**Comment by analogmonster** [comment]
it will have to wait a while I'm afraid as I am mid print now but will send it ASAP

**Comment by MoonshineSG** [comment]
It's midnight here so... take your time. I'll read in the morning :)

**Comment by AlexanderPro29** [comment]
@MoonshineSG I open the link http://pro29.telenet.ru:5000 in a browser and see UI. Nautilus does not see anything except for the video stream, if connected externally. I installed all strictly according to instructions.
My config.yaml file (renamed to .txt):
[config.yaml.txt](https://github.com/MoonshineSG/OctoPrint-Mobile/files/643938/config.yaml.txt)
My haproxy config file (renamed to .txt):
[haproxy.cfg.txt](https://github.com/MoonshineSG/OctoPrint-Mobile/files/643942/haproxy.cfg.txt)
My iOS device is iphone 5s
@analogmonster I use Bitvise SSH Client software for connecting to the raspberry and it is very convenient to copy the necessary files via SFTP.

**Comment by analogmonster** [comment]
@AlexanderPro29 bitvise looks cool, read the message too late for this time but I will download a trial later.  I can see your octoprint UI at that address too so its definitely working.

@MoonshineSG see below.  obviously the xxxx ones I have changed myself

accessControl:
  salt: xxxx
api:
  allowCrossOrigin: true
  key: 'xxxx'
plugins:
  announcements:
    channels:
      _important:
        read_until: 1478614200
      _plugins:
        read_until: 1481241600
  cura:
    cura_engine: /usr/local/bin/cura_engine
  discovery:
    publicPort: 80
    upnpUuid: xxxx
  nautilus:
    _settings_version: 3
  pushover:
    events:
      PrintDone:
        priority: '0'
      PrintFailed:
        priority: '0'
    sound: spacealarm
    token: 'xxxx'
    user_key: xxxx
  softwareupdate:  
    _config_version: 4
    check_providers:
      displayprogress: displayprogress
      navbartemp: navbartemp
      pushover: pushover
      slicer: slicer
      title_status: title_status
    checks:
      octoprint:
        update_folder: /home/pi/OctoPrint
printerProfiles:
  default: anycubic
serial:
  baudrate: 230400
  port: /dev/ttyACM0
server:
  commands:
    serverRestartCommand: sudo service octoprint restart
    systemRestartCommand: sudo shutdown -r now
    systemShutdownCommand: sudo shutdown -h now
  firstRun: false
  secretKey: xxxx
  seenWizards:
    cura: null
slicing:
  defaultProfiles:
    cura: delta_pla
system:
  actions: []
webcam:
  ffmpeg: /usr/bin/avconv
  snapshot: http://127.0.0.1:8080/?action=snapshot
  stream: /webcam/?action=stream

**Comment by MoonshineSG** [comment]
@AlexanderPro29 : i can see the octoprint normal UI , and the Nautilus. I dont get API error... 

On your iphone you use the external url (http://pro29.telenet.ru:5000/) or you use the internal network IP ?

**Comment by AlexanderPro29** [comment]
I used the internal static IP address 192.168.1.153 to connect. Now I tried it and found that an external location is really connected and I see a picture with the camera. But with the internal address is an error "Invalid API key". I also tried other device iPad 2 and there is the same problem.
For outside access to my router set up port forwarding on port 5000 to port 80 internal address. I also tried the settings Nautilus forcibly put port 80, but nothing has changed.

**Comment by AlexanderPro29** [comment]
In Sli3cr program exhibited the same settings to the internal IP address, and it successfully connects and sends the files to OctoPrint.

**Comment by MoonshineSG** [comment]
I am able to connect and see the Nautilus interface. I really don't understand why you have this problem...

**Comment by AlexanderPro29** [comment]
My guess is that the authors OctoPrint something changed and now access to printer management is performed once on the other? I noticed that in the user settings the opportunity to destination user API key.

**Comment by MoonshineSG** [comment]
I'll ask, but unlikely.
So you use the same API key for both, slicer and Nautilus?

**Comment by AlexanderPro29** [comment]
Yes, I use the same key, the same internal address. I have already checked many times, and tried to change the API.

**Comment by MoonshineSG** [comment]
@AlexanderPro29 try to enable "CORS" under Settings/API ...

**Comment by MoonshineSG** [comment]
try to add a file `logging.yaml` in the same folder as `config.yaml`

```
loggers:
  octoprint.plugin:
    level: DEBUG    
  octoprint.server:
    level: DEBUG    
```

try connecting and then send me the log file...

**Comment by AlexanderPro29** [comment]
@MoonshineSG if CORS enabled, Nautilus send "the request timed out".
Today I can not connect from the inside or from the outside. Error "Invalid API key". I did not change any settings at the same time.
I have not figured out how to get to write logs in logging.yaml
I created a file, but he did not write.

**Comment by AlexanderPro29** [comment]
After several reboots Raspberry has access from the outside again and there is no access from the inside by a local address. I enclose a log file.
[octoprint.log.txt](https://github.com/MoonshineSG/OctoPrint-Mobile/files/646841/octoprint.log.txt)

**Comment by MoonshineSG** [comment]
@AlexanderPro29 it's "funny" that I can access it and see the Nautilus UI... Seams to me to be more of a network issue than application.. 
can you try to access it using directly via `http://192.168.1.153:5000` - the OctoPrint port, and this will skip haproxy...

**Comment by AlexanderPro29** [comment]
@MoonshineSG In fact, connecting to pro29.telenet.ru:5000 you just connect to 192.168.1.153:80, because the router simply forwards the packets between the port of raspberry and its external port. I can put any number other than 5000, and it will not change anything. Connect to 192.168.1.153:5000 not work, because the port is closed. I can also connect via pro29.telenet.ru:5000. The question is why the Nautilus is not connected locally to the printer management functions. Another program, such as Sli3cr, successfully working with the API. But she does not use the functions of control over the printer, and only the file upload feature. I think, as is the case with the external, the API error would not have happened if it was an option in Nautilus include only a video stream with a local connection. The reason, it seems to me, in the inaccessibility of the printer control functions due to any changes in OctoPrint code.
I'll try to disable haproxy and see what happens.

**Comment by MoonshineSG** [comment]
OctoPrint listens on port 5000 on you raspberry. haproxy will forward port 80 to 5000 (and URL starting with "webcam" to the streamer 
Your router forwards 5000 to haproxy

**Comment by MoonshineSG** [comment]
also, can you make sure you use the latest version of the ios app, 1.3.3 ?

**Comment by AlexanderPro29** [comment]
@MoonshineSG Port 5000 on my device is closed. I tried to connect to it and disable haproxy, but nothing happened. Haproxy is preinstalled on the distribution OctoPi, I did not change any settings. Perhaps this is some incompatibility with the distribution OctoPi. The version of Nautilus 1.3.3.440

**Comment by MoonshineSG** [comment]
oh, sorry... true, port 5000 it's open, but only locally (127.0.0.1) 

I don't know what else to ask you to check...

**Comment by AlexanderPro29** [comment]
`pi@octopi:~ $ netstat -anp |grep LISTEN
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      407/python
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      462/mjpg_streamer
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp6       0      0 :::8080                 :::*                    LISTEN      462/mjpg_streamer
tcp6       0      0 :::22                   :::*                    LISTEN      -
unix  2      [ ACC ]     STREAM     LISTENING     6205     -                   /run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     7757     -                   /var/run/avahi-daemon/socket
unix  2      [ ACC ]     STREAM     LISTENING     7760     -                   /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     SEQPACKET  LISTENING     6227     -                   /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     6231     -                   /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     58272    1424/systemd        /run/user/1000/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     8929     -                   /var/run/dhcpcd.sock
unix  2      [ ACC ]     STREAM     LISTENING     8931     -                   /var/run/dhcpcd.unpriv.sock`

**Comment by AlexanderPro29** [comment]
@MoonshineSG If you have a Raspberry, you can simulate error on your device. Set distribution OctoPi, switch it to rc/devel and upgrade to the latest version.

**Comment by MoonshineSG** [comment]
I'll do that ... let's see what happens

**Comment by AlexanderPro29** [comment]
Now I tried to install again to another OctoPi Raspberry and a new SD card. Everything was working fine until then, until I switch the branch of the OctoPrint installation on my OctoPi to rc / devel. After the change of branch again the message "Invalid API key". I use this command:
`cd ~/OctoPrint`
`git pull && git checkout rc/devel`
`~/oprint/bin/python setup.py clean`
`~/oprint/bin/python setup.py install`
`sudo service octoprint restart`

Then I went back to the master, but the error "Invalid API key" remained.

**Comment by MoonshineSG** [comment]
Strange, because OctoPrint, "rc/devel" and "master" are identical.

**Comment by 1n5aN1aC** [comment]
Alright, so a bit of an update:

I have no re-installed Octoprint completely yet, but I have reinstalled the plugin, and I was once again able to get it to work for a (shortish) period of time.
  Strangely, I did not use my printer for a week or so, and when I came back, I was able to get it to work again.  But even then, when I tried accessing it again an hour or so later, it no longer worked.

This is all with a test API key that I set myself in the settings of "LOLTESTKEYAPI" or something similar to test it with something completely different.


Anyways, I'm not really too dejected about this, as I've came up with my own ways to keep updated on status while on-the-go.  I'm just letting you know that even though I disappeared, I still haven't really solved this issue, even though it seems to intermittently work from time to time.

**Comment by MoonshineSG** [comment]
trying to solve this...  Would you be willing to install a pre release test ios app ? If yes, you need to install "Test Flight" from Apple and then send me you id and I will send you an invitation to install the   app test version

**Comment by 1n5aN1aC** [comment]
Yeah, sure!
My appleID is: joshuavillwo (-at-) gmail. com

**Comment by MoonshineSG** [comment]
waiting for apple to review the beta. I have little hope this will work, but i don't know what else to try...

**Comment by MoonshineSG** [comment]
I patched one file in OctoPrint files to add some debug statements. (see https://github.com/MoonshineSG/OctoPrint/commit/f85a4159d8159d3a96583e9127f72f2d90df4235)

On your RPi, If you can, replace the file `/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.0-py2.7.egg/octoprint/server/util/__init__.py` with `https://raw.githubusercontent.com/MoonshineSG/OctoPrint/f85a4159d8159d3a96583e9127f72f2d90df4235/src/octoprint/server/util/__init__.py`

Then if you don't have yet, create a file `/home/pi/.octoprint/logging.yaml` with the following content:

```
loggers:
  octoprint.apikey:
    level: DEBUG

```

restarts your OctoPrint service, try to connect with the iOS app, then send me the logs. 

There should be some `2017-01-10 17:47:59,423 - octoprint.apikey - DEBUG - request.headers.get('X-Api-Key') = .... ` entries in the log. Those are of interest.

**Comment by MoonshineSG** [comment]
@1n5aN1aC I'll have another beta that displays the API KEY on the iOS app to make sure it does read it from the Settings and it places it in the http header (it will read the header after setting)

It will be a popup when you open the app but not when switching between apps, you you need to "swipe" it close to see the popup again.

**Comment by 1n5aN1aC** [comment]
Thanks, great idea!

I don't think I have time to do it until tomorrow, but I'm going to try plugging the raspberry in via ethernet, and disabling wifi on all my routers except the one I plug it into.

Just to rule out some more possible network problems.

**Comment by MoonshineSG** [comment]
new iOS test app (483). You need to manually change the template `nautilus_index.jinja2`:

replace
```
var API_KEY_A = "{{ request.headers.get('API_KEY') }}";	
var API_KEY_X = "{{ request.headers.get('X-Api-Key') }}";	
var API_KEY = API_KEY_X ? API_KEY_X : API_KEY_A;
```
with 
```
var API_KEY = "{{request.headers.get('apikey')}}";
```

**Comment by 1n5aN1aC** [comment]
Alright, I got the new iOS test app & replaced the lines you mentioned.

After rebooting both octoprint & the phone app, The pop-up on the app says:

    Loaded 'http://my.domain.name/'
    with headers: {apikey = MYAPIKEY; }

So that looks right, even though it still doesn't work.  :/

In a couple hours, I'll be able to try plugging the raspberry in via ethernet, and disabling wifi on all my routers except the one I plug it into.  I'm beginning to question one aspect about my network more and more, and that should rule it out for sure....

**Comment by MoonshineSG** [comment]
so the iOS app sends the key... but it doesn't get to octoprint... THAT is strange , and I am not sure what can I do... 
I can put the key as a url parameter, but that would expose the key .... for testing that might be a possibility ....

**Comment by 1n5aN1aC** [comment]
Alright, so I connected the printer via wired to my router, and disabled wireless on all my other routers so my phone will connect to that one for sure, and started logging the HTTP traffic, and here is what I found:

Here is a picture of only the http requests that I logged, and I added notes of what the headers were:
![Error](https://i.imgur.com/hbr0RWh.png)

So it doesn't seem like my wired-only experiment made any difference, but I'm seeing the 'apikey' in the headers of the request to "/", just not in the headers of the requests to /api/printerprofiles & /plugin/nautilus/home.  Are those supposed to have them?

**Comment by 1n5aN1aC** [comment]
Oh, just a random thought @MoonshineSG:

X-headers are depreciated anyways, [See here](https://tools.ietf.org/html/rfc6648), maybe some network device is removing them?

EDIT:  actually, that doesn't make much sense, because the X-Api-Key isn't getting *removed*, it's being **set** to "None\r\n" which makes no sense at all.

**Comment by MoonshineSG** [comment]
The use of x-api-key is an OctoPrint requirement to access the API 

Now funny thing happened. I tried to access your server (I can see the IP above) and the key gets populated in the plugin .... (of course I still get an errro as I used the wrong key, but whatever I set is there, doesn't get removed)
So there has to be smth else. Just can't figure it out what causes the header removal in your case... 


Btw, why do you access with an external IP ? ( not that it matters anyway)

I have one more idea that I will try when I get back home later...

**Comment by MoonshineSG** [comment]
I noticed a caching problem on your server. I made raw https request (using "curl") and even if I change the  api key , the javascript read old key from previous requests. Although the iOS reqauet is supposed to send "no-cache" i am not sure it does, so I added some extra "no-cache" headers in the test app. 

Update to build 487 and see if that makes any difference

**Comment by 1n5aN1aC** [comment]
Well, it seems to work at first glance, but I've had it work randomly work for short periods before, (again, that points to a caching issue, I should have thought of that before....) so I'm going to keep checking often to see if it continues working, but I'm guessing it will.

As for why I access with an external DNS name, why wouldn't I?  The main reason why I wanted to get the app working was so I can very easily keep track of my print while I'm on the go, so it should work from pretty much anywhere.

Anyways, I'll keep you updated!

**Comment by MoonshineSG** [comment]
no.. by all means, the external DNS is ok. Had the impression that you try the most basic access.. all good.

anyway, I now have a new version which involves more changes, but it should solve this once and for all. 

I'll send you an email with a new version of the plugin (too many changes to ask you to modify manually) and there will be a new iOS app (build 503) to match the new plugin codes....

**Comment by Marvv90** [comment]
It Work´s now for me !

Step´s to work:

Uinstall Nautilus on Octoprint ( Web -> octopi.local ) 
Restart Pi
Install new with ... from Url ( https://github.com/MoonshineSG/Octoprint-Mobile/archive/master.zip )
Restart Pi

Now it work with Intern Access and Extern Access ... yeah cool ! Thanks

**Comment by 1n5aN1aC** [comment]
@MoonshineSG I updated the iOS app via TestFlite, and now it doesn't work because in the update you released for Nautilus plugin, you forgot to bump the version number.  :)

**Comment by MoonshineSG** [comment]
yup.... rushed work !! 
don't forget to use the plugin i sent by email.

**Comment by 1n5aN1aC** [comment]
@MoonshineSG did you send it to the right e-mail?  I don't think I have received a 1.7.x (or anything really) via e-mail...

(Other issue is fixed, though.  :)

**Comment by MoonshineSG** [comment]
i sent the same address as your apple id. is that wrong ?

**Comment by 1n5aN1aC** [comment]
No, that is not wrong.  

Maybe I lost / deleted it because I mistook it for github notification
e-mails? 

Anyways, it's the @gmail.com address, could you send it again? 

On 2017-01-22 8:09 pm, ǝuıɥsuooɯ wrote:

> i sent the same address as your apple id. is that wrong ? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/MoonshineSG/OctoPrint-Mobile/issues/4#issuecomment-274396685
[2]

**Comment by MoonshineSG** [comment]
Sent.

**Comment by 1n5aN1aC** [comment]
Ahh, your e-mails ended up in gmail's spam bucket. 

No clue how that happened,, but I found them now! 

On 2017-01-22 11:23 pm, ǝuıɥsuooɯ wrote:

> Sent. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/MoonshineSG/OctoPrint-Mobile/issues/4#issuecomment-274416888
[2]

**Comment by 1n5aN1aC** [comment]
@MoonshineSG It works!

It has worked randomly before, so I'll keep testing tonight, and throughout a long print tomorrow before being 100% sure, and closing this issue.

But I do think that the problem has been resolved!

**Comment by MoonshineSG** [comment]
you're now testing with app 1.4 and plugin 1.7 ?

**Comment by 1n5aN1aC** [comment]
Yup!

The version you sent via e-mail, then rebooted.  (Still shows up as 1.6.5 in plugin manager, fyi)

And the latest nautilus available via TestFlight.

**Comment by MoonshineSG** [comment]
yes, since you did a manual install the manager info is not updated (and you will be prompted to update to 1.7 when that is released.

The Nautilus from TestFlight (1.4) would not work with plugin 1.6.5. 

I changed the way the key is handled wot avoid the previous problems so both iOS app and plugin need to be at the right version (iOS app now checks if the plugin is compatible)


Thank you for your patience and your help with the testing!! Hope the effort is justified and you find the app/plugin useful.

**Comment by 1n5aN1aC** [comment]
Alright, it's still working, so I'll consider this issue finally closed!

Thanks for all your work on it.
